[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "16"
  NPM_FLAGS = "--legacy-peer-deps --no-optional"
  PYTHON_VERSION = "3.9"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    skipBuildCommand = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["admin", "member"]}

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"] 