[build]
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"
  publish = ".next"

[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "16"
  NPM_FLAGS = "--legacy-peer-deps --no-optional"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["admin", "member"]}

[functions]
  external_node_modules = ["@supabase/supabase-js"] 